[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_MEIRO_ENDPOINT,VITE_MEIRO_SCRIPT_URL,VITE_MEIRO_PROFILE_API_PROXY_URL,VITE_MEIRO_PROFILE_API_IDENTIFIER_TYPE,VITE_MEIRO_SDK_ENABLED,VITE_MEIRO_DEBUG,VITE_MEIRO_PROFILE_API_ENABLED,VITE_DEMO_DEBUG_ENABLED,MEIRO_PROFILE_API_ENDPOINT"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
